apiVersion: apps/v1
kind: Deployment
metadata:
  name: ping-pong-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ping-pong-app
  template:
    metadata:
      labels:
        app: ping-pong-app
    spec:
      volumes:
        - name: log-persistent
          persistentVolumeClaim:
            claimName: log-claim
      containers:
        - name: ping-pong-app
          image: heclll/ping-pong-app:0.6
          volumeMounts:
            - name: log-persistent
              mountPath: /usr/src/app/persistent