apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-app
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      volumes:
        - name: persistent
          persistentVolumeClaim:
            claimName: log-claim
      containers:
        - name: todo-app
          image: heclll/todo-app:0.8
          volumeMounts:
            - name: persistent
              mountPath: /usr/src/app/persistent