apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-backend
  namespace: project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-backend
  template:
    metadata:
      labels:
        app: todo-backend
    spec:
      containers:
        - name: todo-backend
          image: heclll/todo-backend:1.5
          env:
          - name: PORT
            valueFrom:
              configMapKeyRef:
                name: backend-config
                key: port
          - name: POSTGRES_USER
            value: postgres
          - name: POSTGRES_PASSWORD
            value: postgres
          - name: POSTGRES_DB
            valueFrom:
              configMapKeyRef:
                name: backend-config
                key: postgresDb
          - name: HOST
            valueFrom:
              configMapKeyRef:
                name: backend-config
                key: postgresHost
          - name: DB_PORT
            valueFrom:
              configMapKeyRef:
                name: backend-config
                key: postgresPort