apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-output
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-output
  template:
    metadata:
      labels:
        app: log-output
    spec:
      volumes:
        - name: log-volume
          emptyDir: {}
        - name: log-persistent
          persistentVolumeClaim:
            claimName: log-claim
      containers:
        - name: log-writer
          image: heclll/log-writer:0.5

          volumeMounts:
            - name: log-volume
              mountPath: /usr/src/app/files
            - name: log-persistent
              mountPath: /usr/src/app/persistent
        - name: log-getter
          image: heclll/log-getter:0.7
          volumeMounts:
            - name: log-volume
              mountPath: /usr/src/app/files